[package]
name = "honeycomb-render"
edition.workspace = true
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "Visualization tool for combinatorial maps"
categories.workspace = true
keywords.workspace = true
authors.workspace = true
publish = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
cfg-if.workspace = true
cgmath.workspace = true
env_logger.workspace = true
honeycomb-core.workspace = true
pollster.workspace = true
smaa.workspace = true
wgpu.workspace = true
winit.workspace = true
