[package]
name = "honeycomb-benches"
edition.workspace = true
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Core structure benchmarks"
authors.workspace = true
publish = false

[features]
_single_precision = []

# deps

[dependencies]
cfg-if.workspace = true
honeycomb.workspace = true

[dev-dependencies]
honeycomb-core = { workspace = true, features = ["utils"] }
criterion = { workspace = true, features = ["html_reports"] }
iai-callgrind.workspace = true
rand = { workspace = true, features = ["small_rng"] }

# binaries

[[bin]]
name = "grisubal"
path = "src/grisubal.rs"

# benches

## Iai-callgrind benchmarks

[[bench]]
name = "prof-cmap2-build"
path = "benches/core/cmap2/constructors.rs"
harness = false

[[bench]]
name = "prof-cmap2-basic"
path = "benches/core/cmap2/basic_ops.rs"
harness = false

[[bench]]
name = "prof-cmap2-sewing-unsewing"
path = "benches/core/cmap2/link_and_sew.rs"
harness = false


## Criterion benchmarks

[[bench]]
name = "squaremap-init"
path = "benches/squaremap/init.rs"
harness = false

[[bench]]
name = "squaremap-shift"
path = "benches/squaremap/shift.rs"
harness = false

[[bench]]
name = "squaremap-splitquads"
path = "benches/squaremap/split.rs"
harness = false

[[bench]]
name = "splitsquaremap-init"
path = "benches/splitsquaremap/init.rs"
harness = false

[[bench]]
name = "splitsquaremap-shift"
path = "benches/splitsquaremap/shift.rs"
harness = false

## Kernels benchmarks

[[bench]]
name = "grisubal"
path = "benches/grisubal/time.rs"
harness = false

[[bench]]
name = "grisubal_grid_size"
path = "benches/grisubal/grid_size.rs"
harness = false