[package]
name = "honeycomb-benches"
edition.workspace = true
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Core structure benchmarks"
authors.workspace = true
publish = false

[features]
_single_precision = []

# deps

[dependencies]
cfg-if.workspace = true
honeycomb.workspace = true
rayon = "1.10.0"

[dev-dependencies]
honeycomb-core = { workspace = true, features = ["utils"] }
criterion = { workspace = true, features = ["html_reports"] }
iai-callgrind.workspace = true
rand = { workspace = true, features = ["small_rng"] }

# binaries

[[bin]]
name = "builder"
path = "src/builder.rs"

[[bin]]
name = "grisubal"
path = "src/grisubal.rs"

[[bin]]
name = "shift"
path = "src/shift.rs"

[[bin]]
name = "shift-nc"
path = "src/shift_noncollide.rs"

# benches

## Core benchmarks

[[bench]]
name = "prof-cmap2-build"
path = "benches/core/cmap2/constructors.rs"
harness = false

[[bench]]
name = "prof-cmap2-basic"
path = "benches/core/cmap2/basic_ops.rs"
harness = false

[[bench]]
name = "prof-cmap2-sewing-unsewing"
path = "benches/core/cmap2/link_and_sew.rs"
harness = false

[[bench]]
name = "fetch-icells"
path = "benches/core/cmap2/fetch_icells.rs"
harness = false

## Builder benchmarks

[[bench]]
name = "builder"
path = "benches/builder/time.rs"
harness = false

[[bench]]
name = "builder-grid-size"
path = "benches/builder/grid_size.rs"
harness = false

## Kernels benchmarks

[[bench]]
name = "grisubal"
path = "benches/grisubal/time.rs"
harness = false

[[bench]]
name = "grisubal-grid-size"
path = "benches/grisubal/grid_size.rs"
harness = false

[[bench]]
name = "triangulate-quads"
path = "benches/triangulate/quads.rs"
harness = false

