[package]
name = "honeycomb-examples"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
honeycomb-core = { path = "../honeycomb-core", features = ["benchmarking_utils"] }
honeycomb-render = { path = "../honeycomb-render" }
honeycomb-utils = { path = "../honeycomb-utils" }

[[example]]
name = "memory_usage"
path = "examples/memory_usage/compute.rs"

[[example]]
name = "render_default_no_aa"
path = "examples/render/default_no_aa.rs"

[[example]]
name = "render_default_smaa1x"
path = "examples/render/default_smaa1x.rs"

[[example]]
name = "render_splitsquaremap"
path = "examples/render/splitsquaremap.rs"

[[example]]
name = "render_squaremap"
path = "examples/render/squaremap.rs"