[package]
name = "honeycomb-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
honeycomb-core = { path = "../honeycomb-core" }
honeycomb-render = { path = "../honeycomb-render" }

[[example]]
name = "render_default_no_aa"
path = "examples/render/default_no_aa.rs"