name: Benchmarking

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  rustdoc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable

      # Install the benchmark runner
      - name: Requirements
        run: cargo install --version 0.10.2 iai-callgrind-runner

      # Create a file to write in beforehand
      - name: Chore
        run: sudo mkdir target/iai/honeycomb-utils/ && sudo touch target/iai/honeycomb-utils/bench.out
      
      # Run all benchmarks
      - name: Run 
        run: cargo bench --bench prof-twomap-editing --bench prof-twomap-reading --bench prof-twomap-sewing-unsewing -- --save-summary=json >> target/iai/honeycomb-utils/bench.out
        
      - name: Deploy Results
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: benches/${{ github.ref }}
          publish_dir: ./target/criterion/report
          force_orphan: true