name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_crates:
    name: Build crates for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install hwloc (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhwloc-dev
      - name: Install hwloc (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install hwloc
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build crates
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cargo build --all --no-default-features --features=render,kernels
          else
            cargo build --all --all-features
          fi
  build_examples:
    name: Build examples for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install hwloc (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhwloc-dev
      - name: Install hwloc (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install hwloc
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build examples
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cargo build --examples --no-default-features
          else
            cargo build --examples --all-features
          fi
  build_benchmarks:
    name: Build benchmarks for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install hwloc (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhwloc-dev
      - name: Install hwloc (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install hwloc
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build benchmarks
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cargo build --benches --no-default-features
          else
            cargo build --benches --all-features
          fi
