name: Documentation

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  rustdoc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Need to refine this by specifying components required for doc
      - uses: dtolnay/rust-toolchain@nightly
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.36"
      # Generate user guide first because it removes all existing files
      # from the target directory
      - name: Generate User Guide
        run: mdbook build -d ../target/doc/ user-guide/
      - name: Generate Rust Docs
        run: cargo +nightly doc --all --no-deps --features utils,io

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true