name: Documentation

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  rustdoc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Deps
      - uses: dtolnay/rust-toolchain@nightly
      - uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.36"
      - name: Install hwloc
        run: sudo apt-get install -y libhwloc-dev libudev-dev
      # Generate / using sudo before I'm forced to retry this 83491 times due to CI constraints
      - name: Generate documentation
        run: bash ./docs/build.sh
      # Deploy
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
