name: Documentation

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  rustdoc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Deps
      - uses: dtolnay/rust-toolchain@nightly
      - uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.36"
      - name: Install hwloc
        run: sudo apt-get update && sudo apt-get install -y libhwloc-dev libudev-dev
      # Generate
      - name: Generate rustdoc
        run: cargo +nightly doc --all --no-deps --all-features
      - name: Generate user guide
        run: mdbook build user-guide/
      # Deploy
      - name: Aggregate files
        run: |
          mv user-guide/book target/doc/user-guide && \
          cp docs/index.html target/doc && \
          cp docs/index.css  target/doc
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
